server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE/
          predicates:
            - Path=/CUSTOMER-SERVICE/**
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE/
          predicates:
            - Path=/ACCOUNT-SERVICE/**
        - id: CREDIT-SERVICE
          uri: lb://CREDIT-SERVICE/
          predicates:
            - Path=/CREDIT-SERVICE/**