version: '3.7'
services:
  config-server:
    image: config-service:v1
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    restart: on-failure
    links:
      - eureka-server
    networks:
      - backend
  eureka-server:
    image: eureka-service:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - backend
networks:
  backend:

